name: 'flutter_app'
description: 'App for a pet grooming company.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  firebase_core: ^4.1.1
<<<<<<< HEAD
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
=======
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
>>>>>>> dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  logger: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/dog.png
